-- DATABASE IS CALLED beers_app

BEGIN TRANSACTION;

DROP TABLE IF EXISTS beers_users;
DROP TABLE IF EXISTS beers;
DROP TABLE IF EXISTS users;

CREATE TABLE users
(id BIGSERIAL PRIMARY KEY,
first_name VARCHAR(255) NOT NULL,
username VARCHAR(25) NOT NULL UNIQUE,
email VARCHAR(255) NOT NULL UNIQUE,
password_digest VARCHAR(255) NOT NULL
);

CREATE TABLE beers
(id BIGSERIAL PRIMARY KEY,
beer_name VARCHAR(255) NOT NULL UNIQUE,
beer_type VARCHAR(255) NOT NULL,
beer_image VARCHAR(500),
created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE beers_users
(id BIGSERIAL PRIMARY KEY,
user_id INTEGER NOT NULL REFERENCES users(id),
beer_id INTEGER NOT NULL REFERENCES beers(id)
);

COMMIT;
